## YAML Template.
---
defend: false
roam: false

follow:
  enable: true
  spam: true
  msgs:
  - "The warps on the right are brand new and unexplored!"
  - "If you're looking for a town, take a look at the warps on the left!"
  - "Tell Derp to send me the Doctor's lines already!"
  - "Click on one of the pictures to teleport to its destination!"
  
broadcast:
  enable: true
  delay: 900
  msgs:
  - "Got griefed? Report it to the admins using &6/ag&a!"
  - "Help keep our world tidy! Report floating trees, raided deserts and abandoned buildings using &6/ls&a!"
  - "Keep the world tidy! Report floating trees, raided deserts and abandoned buildings using &6/ls&a!"
  - "Learn more about our server! http://naanpig.zohosites.com"
  - "Meet up on our Discord channel! https://discord.gg/4Qm3wrZ"
  - "If you like our server, &bvote for us! &ehttp://tinyurl.com/vote-for-nyan"