## YAML Template.
---
defend: false
roam: false

follow:
  enable: true
  spam: true
  msgs:
  - "The warps on the right are brand new and unexplored!"
  - "If you're looking for a town, take a look at the warps on the left!"
  - "Tell Derp to send me the Doctor's lines already!"
  - "Click on one of the pictures to teleport to its destination!"
  
broadcast:
  enable: true
  msgs:
  - "Give back to the community by donating items for the &2holiday drop party on Dec 26&a! Drop them off at the Christmas tree."
  - "Don't forget to give Santa your &2wish list&a! Put your list in the hopper under the spawn Christmas tree"
  - "Wanna participate in the &2winter build contest&a? Leave an ag with your name to get a plot! Contest ends January 1st"
  - "If you like our server, &bvote for us! &ahttp://tinyurl.com/vote-for-nyan"